<?php

/**
 * Implementation of hook_init().
 */
function language_access_init() {
  
  global $language;
  $locale = $language->language;
  
  if (!user_access('access language ' . $locale)) {
     $default_language = language_default();     
     $language->prefix = $default_language->prefix;
     drupal_goto('<front>'); // you have to enable at least default language
  }

  return;
}


/**
 * Implementation of hook_permission().
 */
function language_access_permission() {
  $languages = language_list('enabled');
  
  $perms = array();
  
  foreach ($languages[1] as $language) {
    $perms['access language ' . $language->language] = array(
      'title' => t('Access language ' . $language->language), 
    );
  }
  
  return $perms;
}

/**
 * Implementation of hook_language_switch_links_alter().
 */
function language_access_language_switch_links_alter(&$links, $type, $path) {
  
  $languages = language_list('enabled');
  
  foreach ($languages[1] as $language) {
    if (!user_access('access language ' . $language->language)) {
     if (isset($links[$language->language])) unset($links[$language->language]);
    }
  }
}
